config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("enrollment.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("", include("enrollment.students.urls", namespace="students")),
    path("", include("enrollment.messaging.urls", namespace="messaging")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

enrollment/messaging/urls.py
from django.urls import path

from enrollment.messaging import views

app_name = 'messaging'
urlpatterns = [
    path('sms/', views.sms_response, name='sms'),
    path('sms/status/', views.sms_status, name='sms-status'),
    path('messages/', views.MessageListView.as_view(), name='message-list'),
    path('messages/<str:sid>/', views.MessageDetailView.as_view(), name='message-detail'),
]

enrollment/students/urls.py
from django.urls import path

from enrollment.students import views

app_name = 'students'
urlpatterns = [
    path('students/', view=views.StudentListView.as_view(), name='student-list'),
    path('students/<int:pk>/', view=views.StudentDetailView.as_view(), name='student-detail'),
    path('students/add/', views.StudentCreate.as_view(), name='student-add'),
    path('students/<int:pk>/update/', views.StudentUpdate.as_view(), name='student-update'),
    path('students/<int:pk>/delete/', views.StudentDelete.as_view(), name='student-delete'),
    path('addresses/', view=views.AddressListView.as_view(), name='address-list'),
    path('addresses/<int:pk>/', view=views.AddressDetailView.as_view(), name='address-detail'),
    path('addresses/add/', views.AddressCreate.as_view(), name='address-add'),
    path('addresses/<int:pk>/update/', views.AddressUpdate.as_view(), name='address-update'),
    path('addresses/<int:pk>/delete/', views.AddressDelete.as_view(), name='address-delete'),
    path('parents/', view=views.ParentListView.as_view(), name='parent-list'),
    path('parents/<int:pk>/', view=views.ParentDetailView.as_view(), name='parent-detail'),
    path('parents/add/', views.ParentCreate.as_view(), name='parent-add'),
    path('parents/<int:pk>/update/', views.ParentUpdate.as_view(), name='parent-update'),
    path('parents/<int:pk>/delete/', views.ParentDelete.as_view(), name='parent-delete'),
    path('classrooms/', view=views.ClassroomListView.as_view(), name='classroom-list'),
    path('classrooms/<int:pk>/', view=views.ClassroomDetailView.as_view(), name='classroom-detail'),
    path('classrooms/add/', views.ClassroomCreate.as_view(), name='classroom-add'),
    path('classrooms/<int:pk>/update/', views.ClassroomUpdate.as_view(), name='classroom-update'),
    path('classrooms/<int:pk>/delete/', views.ClassroomDelete.as_view(), name='classroom-delete'),
    path('sites/', view=views.SiteListView.as_view(), name='site-list'),
    path('sites/<int:pk>/', view=views.SiteDetailView.as_view(), name='site-detail'),
    path('sites/add/', views.SiteCreate.as_view(), name='site-add'),
    path('sites/<int:pk>/update/', views.SiteUpdate.as_view(), name='site-update'),
    path('sites/<int:pk>/delete/', views.SiteDelete.as_view(), name='site-delete'),
]

enrollment/users/urls.py
from django.urls import path

from enrollment.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

enrollment/students/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django_localflavor_us.models import USStateField
from django.urls import reverse


class Person(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    @property
    def full_name(self):
        "Returns the person's full name."
        return '%s %s' % (self.first_name, self.last_name)

    def __str__(self):
        return self.full_name

    class Meta:
        abstract = True


class Address(models.Model):
    address_1 = models.CharField(("address"), max_length=128)
    address_2 = models.CharField(("address cont'd"), max_length=128, blank=True)
    city = models.CharField(max_length=64)
    state = USStateField()
    zip_code = models.CharField(max_length=5)

    class Meta:
        ordering = ['address_1']

    def __str__(self):
        return f"""
        {self.address_1}
        {self.address_2}
        {self.city} {self.state}, {self.zip_code}
        """

    def get_absolute_url(self):
        return reverse('students:address-detail', kwargs={'pk': self.pk})


class Site(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def get_absolute_url(self):
        return reverse('students:site-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return f'Site {self.name}'

    class Meta:
        ordering = ['name']


class Classroom(models.Model):
    name = models.CharField(max_length=256)
    site = models.ForeignKey(Site, blank=True, null=True, on_delete=models.SET_NULL)

    def get_absolute_url(self):
        return reverse('students:classroom-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return f'Classroom {self.name}'

    class Meta:
        ordering = ['name']


class Student(Person):
    birth_date = models.DateField(blank=True, null=True)
    classrooms = models.ManyToManyField(Classroom)

    class Meta:
        ordering = ['first_name', 'last_name', 'birth_date']

    def get_absolute_url(self):
        return reverse('students:student-detail', kwargs={'pk': self.pk})


class Parent(Person):
    students = models.ManyToManyField(Student)
    email = models.EmailField()
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    address = models.ForeignKey(Address, blank=True, null=True, on_delete=models.SET_NULL)

    def get_absolute_url(self):
        return reverse('students:parent-detail', kwargs={'pk': self.pk})

enrollment/messaging/views.py
import logging
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.urls import reverse
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.template.defaulttags import register

from twilio.twiml.messaging_response import MessagingResponse
from twilio.rest import Client
import pytz
from datetime import datetime as dt

from enrollment.students.models import Parent, Site, Student
from enrollment.messaging.models import Message, MessageStatus
from enrollment.users.mixins import StaffRequiredMixin
from django.conf import settings

logger = logging.getLogger(__name__)
client = Client(settings.TWILIO_SID, settings.TWILIO_TOKEN)


@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)


class MessageListView(LoginRequiredMixin, StaffRequiredMixin, ListView):
    model = Message

    def get_queryset(self):
        return Message.objects.filter(msg_type=Message.INBOUND).filter(parent__isnull=True)


class MessageDetailView(LoginRequiredMixin, StaffRequiredMixin, ListView):
    model = MessageStatus
    template_name = 'messaging/message_detail.html'

    def get_queryset(self):
        sid = self.kwargs['sid']
        return MessageStatus.objects.filter(sid=sid)

    def get_context_data(self):
        context = super().get_context_data()
        context['message_object'] = Message.objects.\
            get(sid=self.kwargs['sid'])
        context['latest_status'] = self.get_queryset().latest()
        context['children_messages'] = Message.objects.\
            filter(parent_id=self.kwargs['sid'])
        children_statuses = MessageStatus.objects.\
            filter(sid__in=context['children_messages'].values_list('sid', flat=True)).\
            order_by('sid', '-datetime').\
            distinct('sid')
        context['children_statuses'] = {
            status.sid: status
            for status in children_statuses
        }
        return context


@csrf_exempt
def sms_status(request):
    # handlle request
    logger.debug(request.POST)
    sid, status = request.POST.get('MessageSid'), request.POST.get('MessageStatus')
    logger.info(f'Message {sid} {status}')

    # add status object
    message_status = MessageStatus(
        status=status,
        sid=sid,
    )
    message_status.save()
    return HttpResponse()


@csrf_exempt
def sms_response(request):
    # only hanlde POST requests
    logger.debug(request.POST)
    if request.method != 'POST':
        return HttpResponse(f'{request.method} request not supported', status=405)

    # parse message
    from_number = request.POST.get('From')
    to_number = request.POST.get('To')
    body = request.POST.get('Body')
    sid = request.POST.get('MessageSid')
    status = request.POST.get('SmsStatus')
    callback = request.build_absolute_uri(reverse('messaging:sms-status'))

    # handle errors
    if not from_number:
        return HttpResponse(f'Missing From phone number', status=400)
    if not to_number:
        return HttpResponse(f'Missing To phone number', status=400)
    if not sid:
        return HttpResponse(f'Missing SID', status=400)
    if not status:
        return HttpResponse(f'Missing SMS status', status=400)

    MessageStatus(status=status, sid=sid).save()

    # create message object for persistence
    message_in = Message(
        sid=sid,
        body=body,
        from_phone_number=from_number,
        to_phone_number=to_number,
        msg_type=Message.INBOUND,
    )
    message_in.save()

    # if recently authenticated then can skip auth this time
    msgs = Message.objects.\
        filter(from_phone_number=from_number).\
        values_list('sid', flat=True)
    try:
        last_pass = MessageStatus.objects.\
            filter(sid__in=msgs, status=MessageStatus.AUTH_PASS).\
            latest()
        logger.debug(f'Last successfal authentication: {last_pass}')
        last_pass = last_pass.datetime
        now = dt.utcnow().replace(tzinfo=pytz.utc)
        delta = now - last_pass
        logger.info(f'''
        Skipping authentication: {delta.seconds:,.1f} seconds since last successfull authentication
        ({settings.AUTH_SECONDS:.1f} seconds required).''')
        MessageStatus(status=MessageStatus.AUTH_SKIP, sid=sid).save()
        auth_required = delta.seconds > settings.AUTH_SECONDS
        if auth_required:
            logger.debug(f'{delta.seconds:,.1f} seconds since last successfull authentication.')
    except MessageStatus.DoesNotExist:
        logger.info('No previous successfull authentications (auth required)')
        auth_required = True

    if not auth_required:
        # no auth required
        logger.debug('Skipping authentication')
        MessageStatus(status=MessageStatus.AUTH_SKIP, sid=sid).save()
        clean_body = body
        resp = f"Your message has been sent"
    elif not body.strip().startswith(settings.SMS_PIN):
        # auth fail
        logger.warning(f'Incorect PIN for SID {sid}')
        MessageStatus(status=MessageStatus.AUTH_FAIL, sid=sid).save()
        send_message(
            body="Incorrect PIN",
            to=from_number,
            callback=callback,
            parent=message_in,
            msg_type=Message.EXCEPTION_AUTH_FAIL,
        )
        return HttpResponse()
    else:
        # auth pass
        clean_body = body[len(settings.SMS_PIN):]
        if auth_required:
            MessageStatus(status=MessageStatus.AUTH_PASS, sid=sid).save()
        resp = f"Your message has been sent"

    # prompt for site if not done recently
    sites = Site.objects.all()
    try:
        # get all messages system sent to this message's sender
        msgs_out = Message.objects.filter(
            to_phone_number=from_number, msg_type=Message.SITE_PROMPT)
        # get the last of those messages to be delivered successfully
        last_out_status = MessageStatus.objects.\
            filter(
                sid__in=msgs_out.values_list('sid', flat=True),
                status=MessageStatus.TWILIO_DELIVERED).\
            latest()
        last_out = msgs_out.get(sid=last_out_status.sid)
        now = dt.utcnow().replace(tzinfo=pytz.utc)
        delta = now - last_out_status.datetime

        # check if a confirmation has been issued more recently
        try:
            msgs_out_conf = Message.objects.filter(
                to_phone_number=from_number, msg_type=Message.CONFIRMATION)
            last_out_conf_status = MessageStatus.objects.\
                filter(
                    sid__in=msgs_out_conf.values_list('sid', flat=True),
                    status=MessageStatus.TWILIO_DELIVERED).\
                latest()
            # last_out_conf = msgs_out.get(sid=last_out_conf_status.sid)
            more_recent_conf = last_out_conf_status.datetime > last_out_status.datetime
        except (Message.DoesNotExist, MessageStatus.DoesNotExist):
            more_recent_conf = False

        if delta.seconds < 60 * 3 and not more_recent_conf:  # TODO: move static numbers to config
            # last message was a site prompt and was recent
            site_prompt_required = False
            # this message is actually a response to the previous prompt
            message_in.parent = last_out
            message_in.save()
        else:
            site_prompt_required = True
            logger.debug(last_out_status.status)
            logger.debug('NEED GROUP PROMPT')
    except (Message.DoesNotExist, MessageStatus.DoesNotExist):
        site_prompt_required = True
        logger.debug('NEED GROUP PROMPT (recent message not found)')
        pass

    if site_prompt_required:
        # get list of sites
        sites = Site.objects.all()
        body = 'Please select a site to send your message to:'
        for site in sites:
            body += f'\n[{site.pk}]: {site.name[:10]}'  # TODO: better templating, sequential index
        # issue site prompt
        send_message(
            body=body,
            to=from_number,
            callback=callback,
            parent=message_in,
            msg_type=Message.SITE_PROMPT,
        )
        return HttpResponse()

    # parse site and clean message
    try:
        site_num = int(body)
    except ValueError:
        MessageStatus(status=MessageStatus.BAD_GROUP, sid=sid).save()
        send_message(
            body="Group selection must be an integer",
            to=from_number,
            callback=callback,
            parent=message_in,
            msg_type=Message.EXCEPTION_BAD_GROUP,
        )
        return HttpResponse()
    if last_out.parent.body.startswith(settings.SMS_PIN):
        clean_body = last_out.parent.body[len(settings.SMS_PIN):]
    else:
        clean_body = last_out.parent.body

    # get all students in specified site
    students_site = Student.objects.filter(classroom__site__pk=site_num)
    if students_site.count() == 0:
        send_message(
            body="No students found for the specified group",
            to=from_number,
            callback=callback,
            parent=message_in,
            msg_type=Message.EXCEPTION_BAD_GROUP,
        )
        return HttpResponse()
    # get all parent phone numbers
    parent_phone_numbers = Parent.objects.\
        filter(students__in=students_site.values_list('pk', flat=True)).\
        values_list('phone_number', flat=True).\
        distinct('phone_number')

    for to_number in parent_phone_numbers:
        send_message(
            body=clean_body,
            to=to_number,
            callback=callback,
            parent=message_in,
        )

    # send message and return empty response
    send_message(
        body=resp,
        to=from_number,
        callback=callback,
        parent=message_in,
        msg_type=Message.CONFIRMATION,
    )
    return HttpResponse()


def send_message(body, to, callback=None, parent=None, msg_type=Message.OUTBOUND):
    twilio_message = client.messages.create(
        body=body,

enrollment/templates/students/address_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Address: {{ object.address_1 }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.address_1 }}</h2>
      <p>
      {{ object.address_1 }}</br>
      {{ object.address_2 }}</br>
      {{ object.city }} {{ object.state }}, {{ object.zip_code }}
      </p>

    </div>
  </div>

<!-- Action buttons -->
<div class="row">
  <div class="col-sm-12">
    <a class="btn btn-outline-primary" href="{% url 'students:address-update' object.pk %}" role="button">Edit</a>
  </div>
</div>
<!-- End Action buttons -->

</div>
{% endblock content %}

enrollment/templates/students/classroom_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Classroom: {{ object.name }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">
      <h2>{{ object }}</h2>
      {% if object.site %}
      <p>
      Site: <a href="{% url 'students:site-detail' object.site.pk %}">{{ object.site.name }}</a>
      </p>
      {% endif %}
      {% if object.student_set.all %}
      <h3>Students</h3>
      {% for student in object.student_set.all %}
      <p><a href="{% url 'students:student-detail' student.pk %}">{{ student.full_name }}</a></p>
      {% endfor %}
      {% endif %}
    </div>
  </div>

<!-- Action buttons -->
<div class="row">
  <div class="col-sm-12">
    <a class="btn btn-outline-primary" href="{% url 'students:classroom-update' object.pk %}" role="button">Edit</a>
    <a class="btn btn-outline-danger" href="{% url 'students:classroom-delete' object.pk %}" role="button">Delete</a>
  </div>
</div>
<!-- End Action buttons -->

</div>
{% endblock content %}

enrollment/templates/students/classroom_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ classroom.name }}{% endblock %}

{% block content %}
  <h1>{{ classroom.fullname }}</h1>
  <form class="form-horizontal" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
	<button type="submit" class="btn btn-primary">
	{% if request.resolver_match.url_name|slice:"-3:" == "add"  %}
	Add
	{% else %}
	Update
        {% endif %}
	</button>
      </div>
    </div>
  </form>
{% endblock %}

enrollment/templates/students/parent_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ parent.fullname }}{% endblock %}

{% block content %}
  <h1>{{ parent.fullname }}</h1>
  <form class="form-horizontal" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <p>Are you sure you want to delete {{ object }}?</p>
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-danger">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

enrollment/templates/students/parent_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Parent: {{ object.full_name }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">
      <h2>{{ object.full_name }}</h2>
      {% if object.email %}<a href="mailto:{{ object.email }}">{{ object.email }}</a>{% endif %}
      {% if object.phone_number %}<p>{{ object.phone_number }}</p>{% endif %}
      {% if object.address %}
      <p>
      {{ object.address.address_1 }}</br>
      {{ object.address.address_2 }}</br>
      {{ object.address.city }} {{ object.address.state }}, {{ object.address.zip_code }}
      </p><a class="btn btn-outline-secondary" href="{% url 'students:address-update' object.address.pk %}" role="button">Edit address</a></p>
      </p>
      {% endif %}
      {% if object.students.all %}
      <h3>Children:</h3>
      {% for child in object.students.all %}
      <p><a href="{% url 'students:student-detail' child.pk %}">{{ child }}</a></p>
      {% endfor %}
      {% endif %}
    </div>
  </div>

<!-- Action buttons -->
<div class="row">
  <div class="col-sm-12">
    <a class="btn btn-outline-primary" href="{% url 'students:parent-update' object.pk %}{% if request.GET.student_id %}?student_id={{ request.GET.student_id }}{% endif %}" role="button">Edit</a>
    <a class="btn btn-outline-secondary" href="{% url 'students:address-add' %}?parent_id={{ object.pk }}" role="button">Create address</a>
    <a class="btn btn-outline-danger" href="{% url 'students:parent-delete' object.pk %}" role="button">Delete</a>
  </div>
</div>
<!-- End Action buttons -->

</div>
{% endblock content %}

enrollment/templates/students/parent_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ parent.fullname }}{% endblock %}

{% block content %}
  <h1>{{ parent.fullname }}</h1>
  <form class="form-horizontal" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

enrollment/templates/students/parent_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Parents{% endblock %}

{% block content %}
<div class="container">
  <h2>Parents</h2>

  <div class="list-group">
    {% for parent in parent_list %}
    <div class="list-group-item">
      <h5 class="list-group-item-heading">{{ parent.full_name }}</h5>
      <a href="{% url 'students:parent-detail' parent.pk %}{% if request.GET.student_id %}?student_id={{ request.GET.student_id }}{% endif %}">
  <button class="btn btn-outline-secondary">View</button>
      </a>
    </div>
    {% endfor %}
  </div>

  <div class="control-group">
    <div class="controls">
      <a href="{% url 'students:parent-add' %}"><button class="btn btn-outline-primary">Add parent</button></a>
    </div>
  </div>

</div>
{% endblock content %}

enrollment/templates/students/site_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ site.name }}{% endblock %}

{% block content %}
  <h1>{{ parent.fullname }}</h1>
  <form class="form-horizontal" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <p>Are you sure you want to delete {{ object }}?</p>
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-danger">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

enrollment/templates/students/site_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Site: {{ object.name }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">
      <h2>{{ object }}</h2>
      {% if object.site %}
      <p>
      {{ object.site }}
      </p>
      {% endif %}
      {% if object.classroom_set.all %}
      <h4>Classrooms</h4>
      {% for classroom in object.classroom_set.all %}
      <p><a href="{% url 'students:classroom-detail' classroom.pk %}">{{ classroom.name }}</a></p>
      {% endfor %}
      {% endif %}
    </div>
  </div>

<!-- Action buttons -->
<div class="row">
  <div class="col-sm-12">
    <a class="btn btn-outline-primary" href="{% url 'students:site-update' object.pk %}" role="button">Edit</a>
    <a class="btn btn-outline-danger" href="{% url 'students:site-delete' object.pk %}" role="button">Delete</a>
  </div>
</div>
<!-- End Action buttons -->

</div>
{% endblock content %}

enrollment/templates/students/site_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ site.name }}{% endblock %}

{% block content %}
  <h1>{{ parent.fullname }}</h1>
  <form class="form-horizontal" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
	<button type="submit" class="btn btn-primary">
	{% if request.resolver_match.url_name|slice:"-3:" == "add"  %}
	Add
	{% else %}
	Update
        {% endif %}
	</button>
      </div>
    </div>
  </form>
{% endblock %}

enrollment/templates/students/site_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Sites{% endblock %}

{% block content %}
<div class="container">
  <h2>Sites</h2>

  <div class="list-group">
    {% for site in site_list %}
    <div class="list-group-item">
      <h5 class="list-group-item-heading">{{ site.name }}</h5>
      <a href="{% url 'students:site-detail' site.pk %}">
  <button class="btn btn-outline-secondary">View</button>
      </a>
    </div>
    {% endfor %}
  </div>

  <div class="control-group">
    <div class="controls">
      <a href="{% url 'students:site-add' %}"><button class="btn btn-outline-primary">Add site</button></a>
    </div>
  </div>

</div>
{% endblock content %}

enrollment/templates/students/student_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ student.fullname }}{% endblock %}

{% block content %}
  <h1>{{ student.fullname }}</h1>
  <form class="form-horizontal" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <p>Are you sure you want to delete {{ object }}?</p>
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-danger">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

enrollment/templates/students/student_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Student: {{ object.full_name }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.full_name }}</h2>
      {% if object.first_name %}
        <p>{{ object.first_name }}</p>
      {% endif %}
      {% if object.classroom %}
      <p>Classroom: <a href="{% url 'students:classroom-detail' object.classroom.pk %}">{{ object.classroom.name }}</a></p>
      {% endif %}
      {% if object.parent_set.all %}
      <h3>Parents:</h3>
      {% for parent in object.parent_set.all %}
      <p><a href="{% url 'students:parent-detail' parent.pk %}">{{ parent }}</a></p>
      {% endfor %}
      <h3>Classrooms:</h3>
      {% for classroom in object.classrooms.all %}
      <p><a href="{% url 'students:classroom-detail' classroom.pk %}">{{ classroom }}</a></p>
      {% endfor %}
      {% endif %}
    </div>
  </div>

<!-- Action buttons -->
<div class="row">
  <div class="col-sm-12">
    {% if not object.parent_set.all %}
    <a class="btn btn-outline-primary" href="{% url 'students:parent-list' %}?student_id={{ object.pk }}" role="button">Select existing parent</a>
    <a class="btn btn-outline-primary" href="{% url 'students:parent-add' %}?student_id={{ object.pk }}" role="button">Add new parent</a>
    {% endif %}
    <a class="btn btn-outline-secondary" href="{% url 'students:student-update' object.pk %}" role="button">Edit</a>
    <a class="btn btn-outline-danger" href="{% url 'students:student-delete' object.pk %}" role="button">Delete</a>
  </div>
</div>
<!-- End Action buttons -->

</div>
{% endblock content %}

enrollment/templates/students/student_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Students{% endblock %}

{% block content %}
<div class="container">
  <h2>Students</h2>

  <div class="list-group">
    {% for student in student_list %}
      <a href="{% url 'students:student-detail' student.pk %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ student.full_name }}</h4>
      </a>
    {% endfor %}
  </div>

  <div class="control-group">
    <div class="controls">
      <a href="{% url 'students:student-add' %}"><button class="btn btn-outline-primary">Add student</button></a>
    </div>
  </div>

</div>
{% endblock content %}